# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import diagnosis
from diagnosis import *
import patientData
from patientData import *
import serviceRecord
from serviceRecord import *
import finance
from finance import *
import setting
from setting import *
import sqlite3
from sqlite3 import *

class Ui_MainWindow(object):
    def __init__(self):
        conn=sqlite3.connect("hospitalDatabase.db")
        c=conn.cursor()
        c.execute("create table if not exists patientDatabase(id integer primary key autoincrement, name text not null, dateOfBirth text, gender text not null, phone text not null, address text, email text)")
        c.execute("create table if not exists serviceDatabase(id integer primary key autoincrement, patientId integer not null, serviceDate text, symptom text, diagnosis text, prescription text, comment text, billingId integer)")
        c.execute("create table if not exists billingDatabase(id integer primary key autoincrement, patientId integer not null, serviceId integer not null, amount integer, comment text)")
        c.execute("create table if not exists hospitalInfoDatabase(hospitalName text, doctorName text, logoDir text)")
        c.execute("select logoDir from hospitalInfoDatabase")
        data=c.fetchone()
        if data==None:
            c.execute("insert into hospitalInfoDatabase(hospitalName, doctorName, logoDir) values(?,?,?)",("Hospital Name (Change in preference)","Doctor Name (Change in preference)","sources\logo.png"))
            c.execute("select logoDir from hospitalInfoDatabase")
            data=c.fetchone()
        self.logoDir=data[0]
        conn.commit()
        conn.close()
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1015)
        font = QtGui.QFont()
        font.setFamily("MingLiU-ExtB")
        font.setPointSize(4)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Diagnosis = QtWidgets.QPushButton(self.centralwidget)
        self.Diagnosis.setGeometry(QtCore.QRect(10, 10, 1261, 681))
        self.Diagnosis.clicked.connect(self.openDiagnose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Diagnosis.setFont(font)
        self.Diagnosis.setAutoFillBackground(False)
        self.Diagnosis.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sources/screenshots/diagnosis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Diagnosis.setIcon(icon)
        self.Diagnosis.setIconSize(QtCore.QSize(1387, 747))
        self.Diagnosis.setObjectName("Diagnosis")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 660, 331, 321))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.patientManagement = QtWidgets.QPushButton(self.centralwidget)
        self.patientManagement.setGeometry(QtCore.QRect(1290, 10, 621, 331))
        self.patientManagement.clicked.connect(self.openPatientData)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.patientManagement.setFont(font)
        self.patientManagement.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("sources/screenshots/patientRecord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patientManagement.setIcon(icon1)
        self.patientManagement.setIconSize(QtCore.QSize(621, 331))
        self.patientManagement.setObjectName("patientManagement")
        self.serviceRecord = QtWidgets.QPushButton(self.centralwidget)
        self.serviceRecord.setGeometry(QtCore.QRect(1290, 360, 621, 331))
        self.serviceRecord.clicked.connect(self.openServiceRecord)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.serviceRecord.setFont(font)
        self.serviceRecord.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("sources/screenshots/serviceRecord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.serviceRecord.setIcon(icon2)
        self.serviceRecord.setIconSize(QtCore.QSize(621, 331))
        self.serviceRecord.setObjectName("serviceRecord")
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(1290, 710, 621, 251))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.setting.setFont(font)
        self.setting.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("sources/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting.setIcon(icon3)
        self.setting.setIconSize(QtCore.QSize(621, 251))
        self.setting.setObjectName("setting")
        self.setting.clicked.connect(self.openSetting)
        self.financial = QtWidgets.QPushButton(self.centralwidget)
        self.financial.setGeometry(QtCore.QRect(650, 710, 621, 251))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.financial.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("sources/imageedit_10_5975279466.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.financial.setIcon(icon4)
        self.financial.setIconSize(QtCore.QSize(621, 251))
        self.financial.setObjectName("financial")
        self.financial.clicked.connect(self.openFinance)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 330, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.linkActivated.connect(self.openDiagnose)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1470, 150, 291, 61))
        self.label_3.linkActivated.connect(self.openPatientData)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1480, 500, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1490, 810, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(810, 810, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 730, 201, 201))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(str(self.logoDir)))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        self.menuNavigate = QtWidgets.QMenu(self.menubar)
        self.menuNavigate.setObjectName("menuNavigate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDiagnosis_Treatment = QtWidgets.QAction(MainWindow)
        self.actionDiagnosis_Treatment.setObjectName("actionDiagnosis_Treatment")
        self.actionDiagnosis_Treatment.triggered.connect(self.openDiagnose)
        self.actionPatient_Management = QtWidgets.QAction(MainWindow)
        self.actionPatient_Management.setObjectName("actionPatient_Management")
        self.actionPatient_Management.triggered.connect(self.openPatientData)
        self.actionService_Record = QtWidgets.QAction(MainWindow)
        self.actionService_Record.setObjectName("actionService_Record")
        self.actionService_Record.triggered.connect(self.openServiceRecord)
        self.actionFinance = QtWidgets.QAction(MainWindow)
        self.actionFinance.setObjectName("actionFinance")
        self.actionFinance.triggered.connect(self.openFinance)
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionSetting.triggered.connect(self.openSetting)
        self.menuNavigate.addAction(self.actionDiagnosis_Treatment)
        self.menuNavigate.addAction(self.actionPatient_Management)
        self.menuNavigate.addAction(self.actionService_Record)
        self.menuNavigate.addAction(self.actionFinance)
        self.menuNavigate.addAction(self.actionSetting)
        self.menubar.addAction(self.menuNavigate.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hospital \n"
                                                    "Management \n"
                                                    "System"))
        self.label_2.setText(_translate("MainWindow", "Diagnosis"))
        self.label_2.linkActivated.connect(self.openDiagnose)
        self.label_3.setText(_translate("MainWindow", "Patient Management"))
        self.label_3.linkActivated.connect(self.openPatientData)
        self.label_4.setText(_translate("MainWindow", "Service Records"))
        self.label_5.setText(_translate("MainWindow", "Setting / Preference"))
        self.label_6.setText(_translate("MainWindow", "Financial Status"))
        self.menuNavigate.setTitle(_translate("MainWindow", "Navigate"))
        self.actionDiagnosis_Treatment.setText(_translate("MainWindow", "Diagnosis"))
        self.actionPatient_Management.setText(_translate("MainWindow", "Patient Management"))
        self.actionService_Record.setText(_translate("MainWindow", "Service Record"))
        self.actionFinance.setText(_translate("MainWindow", "Finance"))
        self.actionSetting.setText(_translate("MainWindow", "Setting/Preference"))

    def openDiagnose(self):
        self.diagnosisWindow=QtWidgets.QMainWindow()
        self.diagUi=Ui_diagnosisWindow()
        self.diagUi.setupUi(self.diagnosisWindow)
        self.diagnosisWindow.show()

    def openPatientData(self):
        self.patientWindow=QtWidgets.QMainWindow()
        self.patientUi=Ui_PatientWindow()
        self.patientUi.setupUi(self.patientWindow)
        self.patientWindow.show()

    def openServiceRecord(self):
        self.serviceRecordWindow=QtWidgets.QMainWindow()
        self.serviceRecordUi=Ui_ServiceRecord()
        self.serviceRecordUi.setupUi(self.serviceRecordWindow)
        self.serviceRecordWindow.show()

    def openFinance(self):
        self.financeWindow=QtWidgets.QMainWindow()
        self.financeUi=Ui_FinanceWindow()
        self.financeUi.setupUi(self.financeWindow)
        self.financeWindow.show()

    def openSetting(self):
        self.settingWindow=QtWidgets.QMainWindow()
        self.settingUi=Ui_Setting()
        self.settingUi.setupUi(self.settingWindow)
        self.settingWindow.show()
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    screens=list()
    sys.exit(app.exec_())


