# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patientSearch.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from sqlite3 import *
from PyQt5.QtCore import QDate, QDateTime, QTime


class Ui_patientSearch(object):
    def __init__(self,mother):
        self.mother=mother
    def setupUi(self, patientSearch):
        patientSearch.setObjectName("patientSearch")
        patientSearch.resize(1183, 870)
        self.Window=patientSearch
        self.currentRow=0
        self.centralwidget = QtWidgets.QWidget(patientSearch)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 80, 1181, 691))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.cellDoubleClicked.connect(self.choosePatient)
        self.searchID = QtWidgets.QLineEdit(self.centralwidget)
        self.searchID.setGeometry(QtCore.QRect(0, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.searchID.setFont(font)
        self.searchID.setText("")
        self.searchID.setAlignment(QtCore.Qt.AlignCenter)
        self.searchID.setObjectName("searchID")
        self.searchID.textChanged.connect(self.doSearchID)
        self.searchName = QtWidgets.QLineEdit(self.centralwidget)
        self.searchName.setGeometry(QtCore.QRect(140, 40, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.searchName.setFont(font)
        self.searchName.setText("")
        self.searchName.setAlignment(QtCore.Qt.AlignCenter)
        self.searchName.setObjectName("searchName")
        self.searchName.textChanged.connect(self.doSearchName)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.searchPhoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.searchPhoneNumber.setGeometry(QtCore.QRect(750, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.searchPhoneNumber.setFont(font)
        self.searchPhoneNumber.setText("")
        self.searchPhoneNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.searchPhoneNumber.setObjectName("searchPhoneNumber")
        self.searchPhoneNumber.textChanged.connect(self.doSearchPhone)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1002, 780, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.choosePatient)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 11, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(720, 10, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        patientSearch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(patientSearch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        patientSearch.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(patientSearch)
        self.statusbar.setObjectName("statusbar")
        patientSearch.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHome.menuAction())
        self.retranslateUi(patientSearch)
        QtCore.QMetaObject.connectSlotsByName(patientSearch)

    def retranslateUi(self, patientSearch):
        _translate = QtCore.QCoreApplication.translate
        patientSearch.setWindowTitle(_translate("patientSearch", "MainWindow"))
        self.pushButton.setText(_translate("patientSearch", "Select"))
        self.label.setText(_translate("patientSearch", "Search by ID"))
        self.label_2.setText(_translate("patientSearch", "Search by Name"))
        self.label_5.setText(_translate("patientSearch", "Search by Phone-Number"))
        self.menuHome.setTitle(_translate("patientSearch", "Home"))
        conn=sqlite3.connect("HospitalDatabase.db")
        c=conn.cursor()
        c.execute("select id, name, dateOfBirth, gender, phone from patientDatabase")
        patients=c.fetchall()
        conn.close()
        self.fillTable(patients)


    def choosePatient(self):
        id=self.tableWidget.item(self.tableWidget.currentRow(),0).text()
        self.mother.loadPatient(id)
        self.Window.close()

    def doSearchID(self):
        conn=sqlite3.connect("hospitalDatabase.db")
        c=conn.cursor()
        c.execute("select id, name, dateOfBirth, gender, phone from patientDatabase where id like ?",("%"+self.searchID.text()+"%",))
        data=c.fetchall()
        conn.close()
        self.fillTable(data)

    def doSearchName(self):
        conn=sqlite3.connect("hospitalDatabase.db")
        c=conn.cursor()
        c.execute("select id, name, dateOfBirth, gender, phone from patientDatabase where name like ?",("%"+self.searchName.text()+"%",))
        data=c.fetchall()
        conn.close()
        self.fillTable(data)

    def doSearchPhone(self):
        conn=sqlite3.connect("hospitalDatabase.db")
        c=conn.cursor()
        c.execute("select id, name, dateOfBirth, gender, phone from patientDatabase where phone like ?",("%"+self.searchPhoneNumber.text()+"%",))
        data=c.fetchall()
        conn.close()
        self.fillTable(data)
        
    def fillTable(self, patients):
        conn=sqlite3.connect("hospitalDatabase.db")
        c=conn.cursor()
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.setRowCount(len(patients))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setColumnWidth(0,30)
        self.tableWidget.setColumnWidth(1,300)
        self.tableWidget.setColumnWidth(2,180)
        self.tableWidget.setColumnWidth(3,60)
        self.tableWidget.setColumnWidth(4,120)
        self.tableWidget.setColumnWidth(5,290)
        self.tableWidget.setColumnWidth(6,180)
        self.tableWidget.setHorizontalHeaderLabels(["ID", "Name","Date of Birth","Age","Gender", "Phone Number","Last visit"])
        for i in range(len(patients)):
            c.execute("select serviceDate from serviceDatabase where patientId=?",(patients[i][0],))
            dates=c.fetchall()
            if len(dates)>0:
                toQDate=list(map(lambda a:QDateTime.fromString(a[0].split(" ",1)[1],"M d hh:mm:ss yyyy"),dates))
                copyList=toQDate.copy()
                minDay=min(map(lambda a:a.daysTo(QDateTime.currentDateTime()),copyList))
                lastVisit=QDate.currentDate().addDays((minDay)*(-1))
                lastVisitItem=QtWidgets.QTableWidgetItem(lastVisit.toString().replace(" ","-"))
                lastVisitItem.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget.setItem(i,6,lastVisitItem)
            id=QtWidgets.QTableWidgetItem(str(patients[i][0]))
            id.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i,0,id)
            name=QtWidgets.QTableWidgetItem(patients[i][1])
            name.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i,1,name)
            age=QtWidgets.QTableWidgetItem(str(QDate.currentDate().getDate()[0]-int(patients[i][2].split("-")[0])))
            age.setTextAlignment(QtCore.Qt.AlignCenter)
            dobString=(patients[i][2].split("-")[0],patients[i][2].split("-")[1],patients[i][2].split("-")[2])
            dob=QtWidgets.QTableWidgetItem(str(dobString[0])+" / "+str(dobString[1])+" / "+str(dobString[2]))
            dob.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i,2,dob)
            self.tableWidget.setItem(i,3,age)
            gender=patients[i][3]
            genderItem=QtWidgets.QTableWidgetItem(gender)
            genderItem.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i,4,genderItem)
            pNumber=QtWidgets.QTableWidgetItem(str(patients[i][4]))
            pNumber.setTextAlignment(QtCore.Qt.AlignCenter)
            self.tableWidget.setItem(i,5,pNumber)
        conn.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    patientSearch = QtWidgets.QMainWindow()
    ui = Ui_patientSearch("temp")
    ui.setupUi(patientSearch)
    patientSearch.show()
    sys.exit(app.exec_())
